external:
  hostname: external-service.yourdomain.com

service:
  name:
  port:

ingress:
  hostname: external-service-expose.yourdomain.com
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # important

tls:
  enabled: true
  secretName: tls-secret
