apiVersion: v1
kind: Service
metadata:
  name: webfinger
spec:
  selector:
    app: webfinger
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}