apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.secret.storeName }}
    kind: {{ .Values.secret.storeKind }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Merge
  data:
  - secretKey: "oidc.keycloak.clientSecret"
    remoteRef:
      key: secret/data/argocd/oidc/secret
      property: "oidc.keycloak.clientSecret"



