apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.secret.storeName }}
    kind: {{ .Values.secret.storeKind }}
  target:
    name: {{ .Values.secret.target | default .Values.secret.name }}
  data:
  - secretKey: {{ .Values.secret.key }}
    remoteRef:
      key: {{ .Values.secret.remoteKey }}
      property: {{ .Values.secret.remoteProperty }}
