apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
  data:
  - secretKey: admin-password
    remoteRef:
      key: {{ .Values.secretPath }}/data/keycloak/secret
      property: admin-password
  - secretKey: management-password
    remoteRef:
      key: {{ .Values.secretPath }}/data/keycloak/secret
      property: management-password
  - secretKey: tls-keystore-password
    remoteRef:
      key: {{ .Values.secretPath }}/data/keycloak/secret
      property: tls-keystore-password
  - secretKey: tls-truestore-password
    remoteRef:
      key: {{ .Values.secretPath }}/data/keycloak/secret
      property: tls-truestore-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: keycloak-postgresql-secret
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.secretPath }}/data/keycloak/postgresql/secret
      property: postgresql-password
  - secretKey: postgres-password
    remoteRef:
      key: {{ .Values.secretPath }}/data/keycloak/postgresql/secret
      property: postgresql-postgres-password
