{{- if (include "lldap.generate.configMap" .) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lldap.name" . }}-cm
  labels: {{ include "lldap.labels" (merge (dict "Labels" .Values.configMap.labels) .) | nindent 4 }}
  {{- with $annotations := include "lldap.annotations" (merge (dict "Annotations" .Values.configMap.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.configMap.mountAsFile }}
  lldap_config.toml: |-
    {{- range $key, $val := .Values.config }}
    {{ $key }} = {{ $val }}
    {{- end }}
    database_url = {{ include "lldap.generate.dburl" . }}
    {{- if .Values.smtp }}
    [smtp_options]
      {{- range $key, $val := (omit .Values.smtp "enabledSecret") }}
    {{ $key }} = {{ $val }}
      {{- end }}    
    {{- end }}
    [ldaps_options]
    {{- range $key, $val := fromYaml (include "lldap.ldaps.options" .) }}
    {{ $key }} = {{ $val }}
    {{- end }}
  {{- else -}}
    {{- if .Values.config -}}
      {{- $configs := omit .Values.config "ldap_user_pass" "jwt_secret" "key_seed" }}
      {{- range $key, $val := $configs }}
    {{ printf "LLDAP_%s" (upper $key) }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
    {{- if (include "lldap.ldaps.enabled" .)}}
    {{- range $key, $val := fromYaml (include "lldap.ldaps.options" .) }}
    {{ printf "LLDAP_LDAPS_%s" (upper $key) }}: {{ $val  }}
    {{- end }}
    {{- end }}
    {{- if .Values.smtp -}}
      {{- $smtp := omit .Values.smtp "password" "enabledSecret" }}
      {{- range $key, $val := $smtp }}
    {{ printf "LLDAP_SMTP_OPTIONS_%s" (upper $key) }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
