{{ if (include "lldap.enabled.networkPolicy" .) -}}
---
apiVersion: {{ include "capabilities.apiVersion.networkPolicy" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "lldap.name" . }}
  labels: {{ include "lldap.labels" (merge (dict "Labels" .Values.networkPolicy.labels) .) | nindent 4 }}
  {{- with $annotations := include "lldap.annotations" (merge (dict "Annotations" .Values.networkPolicy.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "lldap.matchLabels" . | nindent 6 }}
  policyTypes: {{ toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- with $ingress := .Values.networkPolicy.ingress }}
  ingress: {{ toYaml $ingress | nindent 4 }}
  {{- end }}
  {{- with $egress := .Values.networkPolicy.egress }}
  egress: {{- toYaml $egress | nindent 4 }}
  {{- end }}
{{- end -}}