{{- if (include "lldap.enabled.podDisruptionBudget" .) }}
---
apiVersion: {{ include "capabilities.apiVersion.podDisruptionBudget" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "lldap.name" . }}
  labels: {{ include "lldap.labels" (merge (dict "Labels" .Values.podDisruptionBudget.labels) .) | nindent 4 }}
  {{- with $annotations := include "lldap.annotations" (merge (dict "Annotations" .Values.podDisruptionBudget.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels: {{- include "lldap.matchLabels" . | nindent 6 }}
{{- end -}}