{{ if (include "lldap.enabled.secret" .) -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "lldap.name" .)) | default dict -}}
{{- $secretData := $secret.data | default dict -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lldap.name" . }}-secret
  labels: {{ include "lldap.labels" (merge (dict "Labels" .Values.secret.labels) .) | nindent 4 }}
  {{- with $annotations := include "lldap.annotations" (merge (dict "Annotations" .Values.secret.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.config.jwt_secret -}}
  LLDAP_JWT_SECRET: {{ .Values.config.jwt_secret | b64enc }}
  {{- end }}
  {{- if .Values.config.ldap_user_pass -}}
  LLDAP_LDAP_USER_PASS: {{ .Values.config.ldap_user_pass | b64enc }}
  {{- end }}
  {{- if .Values.config.key_seed -}}
  LLDAP_KEY_SEED: {{ .Values.config.key_seed | b64enc }}
  {{- end }}
  {{- if .Values.smtp -}}
    {{- if .Values.smtp.password -}}
  LLDAP_SMTP_OPTIONS_PASSWORD: {{ .Values.smtp.password | b64enc }}
    {{- end }}
  {{- end }}
  {{- if ne (include "lldap.generate.dbtype" .) "sqlite" }}
    {{- with .Values.database }}
      {{- if .mysql.enabled }}
  LLDAP_DATABASE_URL: {{print "mysql://" .mysql.username ":" .mysql.password "@" .mysql.host ":" .mysql.port "/" .mysql.database | b64enc }}
      {{- end }}
      {{- if .postgres.enabled }}
  LLDAP_DATABASE_URL: {{print "postgres://" .postgres.username ":" .postgres.password "@" .postgres.host ":" .postgres.port "/" .postgres.database | b64enc }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}