apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.name" . }}-service
  labels: {{ include "lldap.labels" (merge (dict "Labels" .Values.service.labels) .) | nindent 4 }}
  {{- with $annotations := include "lldap.annotations" (merge (dict "Annotations" .Values.service.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with $ip := .Values.service.clusterIP }}
  clusterIP: {{ $ip }}
  {{- end }}
  {{- with $ips := .Values.service.externalIPs }}
  externalIPs: {{ toYaml $ips | nindent 4 }}
  {{- end }}
  sessionAffinity: {{ default "None" .Values.service.sessionAffinity }}
  selector: {{- include "lldap.matchLabels" . | nindent 4 }}
  ports:
    - name: ldap
      protocol: TCP
      port: {{ include "lldap.service.ldapPort" . }}
      targetPort: 3890
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: ldaps
      protocol: TCP
      port: {{ include "lldap.service.ldapsPort" . }}
      targetPort: 6360
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: web
      protocol: TCP
      port: {{ include "lldap.service.port" . }}
      targetPort: 17170
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
