{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "lldap.name" .) .Values.rbac.serviceAccountName }}
  labels: {{ include "lldap.labels" (merge (dict "Labels" .Values.rbac.labels) .) | nindent 4 }}
  {{- with $annotations := include "lldap.annotations" (merge (dict "Annotations" .Values.rbac.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- end }}