{{ $storeName := .Values.storeName }}
{{ $storeKind := .Values.storeKind }}
{{ $refreshInterval := .Values.refreshInterval }}
{{ $namespace := .Release.Namespace }}
{{ $hasPath := .Values.hasPath }}
{{ $secretPath := .Values.secretPath }}
{{- range .Values.secrets }}
{{ $remoteKey := .remoteKey | default .name }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $namespace }}
spec:
  refreshInterval: {{ .refreshInterval | default $refreshInterval }}
  secretStoreRef:
    name: {{ .storeName | default $storeName }}
    kind: {{ .storeKind | default $storeKind }}
  target:
    name: {{ .target | default .name }}
{{- if .creationPolicy }}    
    creationPolicy: {{ .creationPolicy }}
{{- end }}
{{- if .targetTemplate }}    
    template: 
    {{ .targetTemplate | toYaml | nindent 6 }}
{{- end }}
  data:
{{- range .items }}
  - secretKey: {{ .secretKey }}
    remoteRef:
{{- if or .hasPath $hasPath }}
      key: {{ .secretPath | default $secretPath}}/{{ .remoteKey | default $remoteKey }}
{{- else }}
      key: {{ .remoteKey | default $remoteKey }}
{{- end}}      
      property: {{ .remoteProperty | default .secretKey }}
{{- end }}
---
{{- end}}