apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobName }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.jobName }}-sa
      initContainers:
      {{- if .Values.waitForVault.enabled }}
      - name: wait-for-vault
        image: {{ .Values.waitForVault.repository }}:{{ .Values.waitForVault.tag }}
        command:
          - /bin/sh
          - -c
          - |
            echo "Aspetto che {{ .Values.waitForVault.podName }} sia Ready..."
            if kubectl wait --for=condition=Ready pod/{{ .Values.waitForVault.podName }} --namespace={{ .Values.namespace }} --timeout={{ .Values.waitForVault.timeoutSeconds }}s; then
              echo "Vault è pronto!"
            else
              echo "❌ Timeout: Vault non è diventato Ready entro {{ .Values.waitForVault.timeoutSeconds }}s"
              exit 1
            fi
      {{- end }}
      {{- if .Values.waitForSecret.enabled }}
      - name: wait-for-secret
        image: {{ .Values.waitForSecret.repository }}:{{ .Values.waitForSecret.tag }}
        command:
          - /bin/sh
          - -c
          - |
            echo "Aspetto che {{ .Values.vault.rootTokenSecret.name }} sia Created..."
            if kubectl wait --for=create secret/{{ .Values.vault.rootTokenSecret.name }} --namespace={{ .Values.namespace }} --timeout={{ .Values.waitForSecret.timeoutSeconds }}s; then
              echo "Secret è pronto!"
            else
              echo "❌ Timeout: Secret non è diventato Ready entro {{ .Values.waitForSecret.timeoutSeconds }}s"
              exit 1
            fi
      {{- end }}
      - name: prepare-script
        image: {{ .Values.prepareScript.repository }}:{{ .Values.prepareScript.tag }}
        command:
          - /bin/sh
          - -c
          - |
            cp {{ .Values.scriptDir }}/*.sh /workdir
            chmod +x /workdir/{{ .Values.scriptFile }}
        volumeMounts:
        {{- if .Values.nfs.enabled }}
        - name: nfs-volume
          mountPath: {{ .Values.scriptDir }}
        {{- else }}
        - name: script-volume
          mountPath: {{ .Values.scriptDir }}
        {{- end }}
        - name: workdir-volume
          mountPath: /workdir
        {{- if .Values.extraFiles.enabled }}
        - name: extra-files
          mountPath: {{ .Values.extraFiles.mountPath | quote }}
          readOnly: {{ .Values.extraFiles.readOnly | default true }}
        {{- end }}
      containers:
      - name: vault-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: 
          - "/bin/sh"
          - "{{ .Values.scriptFile }}"
        workingDir: /workdir
        env:
        - name: VAULT_ADDR
          value: {{ .Values.vault.address | quote }}
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.vault.rootTokenSecret.name }}
              key: {{ .Values.vault.rootTokenSecret.key }}
        volumeMounts:
        - name: vault-tls
          mountPath: /vault/tls
          readOnly: true
        - name: workdir-volume
          mountPath: /workdir
        {{- if .Values.extraFiles.enabled }}
        - name: extra-files
          mountPath: {{ .Values.extraFiles.mountPath | quote }}
          readOnly: {{ .Values.extraFiles.readOnly | default true }}
        {{- end }}
      volumes:
      - name: vault-tls
        secret:
          defaultMode: 420
          secretName: {{ .Values.vault.tlsSecret.name }}
      - name: workdir-volume
        emptyDir: {}
      - name: vault-token
        secret:
          secretName: {{ .Values.vault.rootTokenSecret.name }}
          items:
          - key: {{ .Values.vault.rootTokenSecret.key }}
            path: {{ .Values.vault.rootTokenSecret.fileName }}
      {{- if .Values.nfs.enabled }}
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: {{ .Values.jobName }}-nfs-pvc
      {{- else }}
      - name: script-volume
        configMap:
          name: {{ .Values.jobName }}-cm
      {{- end }}
      {{- if .Values.extraFiles.enabled }}
      - name: extra-files
        {{- if .Values.extraFiles.configMap }}
        configMap:
          name: {{ .Values.extraFiles.configMap }}
        {{- else if .Values.extraFiles.secret }}
        secret:
          secretName: {{ .Values.extraFiles.secret }}
        {{- else if .Values.extraFiles.existingVolume }}
        persistentVolumeClaim:
          claimName: {{ .Values.extraFiles.existingVolume }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 1  