apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.example.local
    path: /exports/vault-scripts