apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jobName }}-nfs-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi