{{- if not .Values.script.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scheduledScriptJob.scriptConfigMapName" . }}
data:
  {{ .Values.script.fileName }}: |-
{{ .Values.script.content | indent 4 }}
{{- with .Values.config.data }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
