apiVersion: v1
description: Helm chart for addon resources for vault operator
name: addons-vault-operator
version: 0.0.4
dependencies:
  - name: vault-operator
    repository: oci://ghcr.io/bank-vaults/helm-charts/vault-operator
    version: 1.21.2
    