pv:
  # -- enable PV
  enabled: false
  # -- name  of the PV
  name: vault-data
  # -- server for PV in case of nfs
  server: 192.168.1.6
  # -- path for PV in case of nfs
  path: "/nfs/vaultdata"
  # -- storage class name
  storageClassName: nfs-sc-vault-data

cr:
  # -- label for the vault
  label: vault
  # -- name of the vault
  name: vault
  # -- image of the vault
  vaultImage: hashicorp/vault:1.15.1
  # -- number of instances of vault
  size: 1
  # -- image of bank-vaults
  # bankVaultsImage: ghcr.io/banzaicloud/bank-vaults:1.20.3
  # -- annotation for the vault pod
  vaultAnnotations: "vault"
  # -- annotation for the vault configurer pod
  vaultConfigurerAnnotations: "vaultconfigurer"

  caNamespaces:
    - "*"

  ingress:
    # -- enable the ingress
    enabled: false
    # -- annnotation for the ingress
    annotations: {}
    # -- enable conmfiguration for traefik
    traefik: false
    # -- ingress class name
    ingressClassName: nginx
    # -- hostname
    hostname: vault.local
    # -- service name
    serviceName: vault
    tls:
      # -- enable TLS for the ingress
      enabled: true
      # -- secret for TLS
      secretName: vault-tls

  config:
    storage:
      raft:
        path: /vault/data
        # retry_join:
        #   leader_api_addr: "https://vault-0.vault:8200"
        # autopilot:
        #  cleanup_dead_servers: "true"
        #  last_contact_threshold: "200ms"
        #  last_contact_failure_threshold: "10m"
        #  max_trailing_logs:  250000
        #  min_quorum: 1
        #  server_stabilization_time: "10s"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    ui: true

  # -- additional volumes
  # additionalVolumes:
  # -- additional volumes mounts
  # additionalVolumesMount:

  claim:
    # -- name of the PVC
    name: vault-raft
    # -- path of the PVC
    path: /vault/data
    # -- storage
    storage: 1Gi

  # -- enable velero config
  veleroEnabled: false

  # -- External config for the vault
  externalConfig:
    policies:
    - name: allow_secrets
      rules: path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }
    auth:
    - type: kubernetes
      roles:
        - name: externalsecrets
          bound_service_account_names: ["vault-auth"]
          bound_service_account_namespaces: ["*"]
          policies: allow_secrets
          ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: Secrets for prod env.
        options:
          version: 2
  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug

rbac:
  # -- SA name
  serviceAccountName: vault
  # -- role name
  roleName: vault
  # -- name of the role binding
  roleBindingName: vault
