apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.secret.storeName }}
    kind: {{ .Values.secret.storeKind }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Merge
  data:
  - secretKey: "client-info-secret"
    remoteRef:
      key: secret/data/synology-csi/client-info-secret
      property: "client-info.yaml"
