apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.secret.storeName }}
    kind: {{ .Values.secret.storeKind }}
  target:
    name: {{ .Values.secret.target | default .Values.secret.name }}
  data:
  - secretKey: {{ .Values.secret.clientId.key }}
    remoteRef:
      key: {{ .Values.secret.remoteSecret.key }}
      property: {{ .Values.secret.clientId.property }}
  - secretKey: {{ .Values.secret.clientSecret.key }}
    remoteRef:
      key: {{ .Values.secret.remoteSecret.key }}
      property: {{ .Values.secret.clientSecret.property }}
  - secretKey: {{ .Values.secret.cookieSecret.key }}
    remoteRef:
      key: {{ .Values.secret.remoteSecret.key }}
      property: {{ .Values.secret.cookieSecret.property }}
