jobName: vault-config-job
namespace: vault

waitForVault:
  enabled: true
  repository: bitnami/kubectl
  tag: latest
  podName: vault-0
  timeoutSeconds: 300

waitForSecret:
  enabled: true
  repository: bitnami/kubectl
  tag: latest
  timeoutSeconds: 300

prepareScript:
  repository: busybox
  tag: latest


vault:
  address: "http://vault-0.vault.svc.cluster.local:8200"
  tlsSecret:
    name: vault-tls
  rootTokenSecret:
    name: vault-unseal-keys
    key: vault-root
    mountPath: /vault/creds
    fileName: vault-root-token

scriptFile: "script.sh"
scriptDir: "/scripts"
script: |
  export VAULT_ADDR="{{ .Values.vault.address }}"
  VAULT_ROOT_TOKEN=$(cat {{ .Values.vault.rootTokenSecret.mountPath }}/{{ .Values.vault.rootTokenSecret.fileName }})
  vault login $VAULT_ROOT_TOKEN
  vault secrets enable -path=kv kv
  vault kv put kv/mysecret password="supersecret"

# Additional files volume configuration
# Set enabled: true and specify either configMap, secret, or existing volume to mount files into the job
extraFiles:
  enabled: false
  # One of configMap, secret, or existingVolume must be set if enabled is true
  # -- Name of ConfigMap containing files (optional)
  configMap: ""
  # -- Name of Secret containing files (optional)
  secret: ""
  # -- Name of an existing volume to mount (optional)
  existingVolume: ""
  # -- Path to mount the extra files
  mountPath: "/extra-files"
  readOnly: true

image:
  repository: hashicorp/vault
  tag: latest

nfs:
  enabled: true
  server: nfs.example.local
  path: /exports/vault-scripts
  storage: 1Gi
  accessModes:
    - ReadOnlyMany

customExtraFilesSecret:
  enabled: false
  name: custom-extra-files-secret
  stringData: {}
