webfinger:
  subject: admin@domain.com
  issuer: https://iam.domain.com

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: iam.domain.com
