{{ $email := .Values.email}}
{{ $gcpProject := .Values.gcpProject }}
{{ $secret := .Values.serviceAccountSecret }}
{{- range .Values.clusterissuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ required "The name of the cluster issuer is required" .name }}
spec:
{{- $type := required "The type of cluster issuer is required" .type }}
{{- if eq $type "acme" }}
  acme:
    # The ACME server URL
    server: {{ .server }}
    # Email address used for ACME registration
    email: {{ $email }}  
    privateKeySecretRef:
      name: {{ .name }}
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: {{ $gcpProject }}
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: {{ .saSecretName | default $secret.name }}
            key: {{ .saSecretKey | default $secret.key }}
{{- end }}
{{- if eq $type "vault" }}
  vault:
    path: {{ .path }}
    server: {{ .server }}
    auth:
      kubernetes:
        role: {{ .role }}
        mountPath: {{ .mountPath }}
        serviceAccountRef:
          name: vault-issuer
{{- end }}
---
{{- end }}