{{ $email := .Values.email}}
{{ $gcpProject := .Values.gcpProject }}
{{ $secret := .Values.secret }}
{{- range .Values.clusterissuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .server }}
    # Email address used for ACME registration
    email: {{ $email }}  
    privateKeySecretRef:
      name: {{ .name }}
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: {{ $gcpProject }}
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: {{ $secret.name }}
            key: {{ $secret.key }}
---
{{- end }}