image:
  repository: bmauter/alpine-samba-client
  tag: latest
sambaSecret: samba-credentials
scriptConfigMap: sync-script
schedule: "0 0 * * *"
samba:
  server: "//samba.example.com/share"
targetFile: "pv-list.txt"
