apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.server }}
      path: {{ .Values.secretStore.secretPath }}
      version: "v2"
      caProvider:
        type: Secret
        name: {{ .Values.secretStore.caProvider.secretName }}
        key: ca.crt
        namespace: {{ .Values.secretStore.caProvider.namespace }}
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        # tokenSecretRef:
        #  name: "vault-token"
        #  namespace: vault
        #  key: "token"
        ## Authenticate against Vault using a Kubernetes ServiceAccount
        ## token stored in a Secret.
        ## https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          ## Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          ## A required field containing the Vault Role to assume.
          role: {{ .Values.secretStore.auth.role }}
          ## Optional service account field containing the name
          ## of a kubernetes ServiceAccount
          serviceAccountRef:
            name: {{ .Values.secretStore.sa.name }}
            namespace: {{ .Values.secretStore.sa.namespace }}
            ## Optional secret field containing a Kubernetes ServiceAccount JWT
            ##  used for authenticating with Vault
          #secretRef:
          #  name: "vault-auth-secret"
          #  namepsace: vault
          #  key: "vault"