apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include  "chart.name" . }}
  annotations: {{ .Values.annotations | toYaml | nindent 4}}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include  "service.name" . }}
            port:
              number: {{ .Values.service.port }}
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.tls.secretName }}
  {{- end }}
