{{- $saName := .Values.rbac.serviceAccountName | default .Release.Name  -}}
{{- $roleName := .Values.rbac.roleName | default .Release.Name -}}
{{- $roleBindingName := .Values.rbac.roleBindingName | default .Release.Name -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $roleName }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update", "patch"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $roleBindingName }}
roleRef:
  kind: Role
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}

---

# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $saName }}-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}