apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin
  data:
  - secretKey: admin-user
    remoteRef:
      key: secret/data/grafana/admin
      property: admin-user
  - secretKey: admin-password
    remoteRef:
      key: secret/data/grafana/admin
      property: admin-password



