image:
  repository: bmauter/alpine-samba-client
  tag: latest
certificateSecret: certificate-secret
sambaSecret: samba-credentials
scriptConfigMap: sync-script
schedule: "0 0 * * *"
samba:
  server: "//samba.example.com/share"
  certTargetFile: "cert.pem"
  keyTargetFile: "key.pem"
